### ISSUE TITLE
oceanbase 同步到mysql 异常 unknow java.sql.Types - 0

### ISSUE THREAD

**Issue by emf1002** [oceanbase/canal#18]
异常信息如下：
> pid:1 nid:1 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: java.lang.IllegalArgumentException: unknow java.sql.Types - 0
    at com.alibaba.otter.node.etl.common.db.utils.SqlUtils.stringToSqlValue(SqlUtils.java:145)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doPreparedStatement(DbLoadAction.java:779)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.access$800(DbLoadAction.java:523)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2$1.setValues(DbLoadAction.java:634)
    at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:816)
    at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
    at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
    at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:631)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:623)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:551)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:462)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:275)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:161)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
    at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
    at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
    at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
    at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by whhe** [comment]
可否提供下出问题的变动内容，比如操作类型、表结构或者出问题的字段类型

**Comment by whhe** [comment]
可否提供下出问题的变动内容，比如操作类型、表结构或者出问题的字段类型

**Comment by emf1002** [comment]
EventColumn[index=0,columnType=12,columnName=ID,columnValue=8421e71e140718d6cf7eac91591eeaa8,isNull=false,isKey=true,isUpdate=true]
---oldPks

---Columns
    EventColumn[index=1,columnType=0,columnName=OPERATOR_IP,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=2,columnType=0,columnName=OPERATOR_ID,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=3,columnType=0,columnName=OPERATOR_NAME,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=4,columnType=0,columnName=TYPE,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=5,columnType=12,columnName=STATUS,columnValue=0001,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=6,columnType=93,columnName=TIME,columnValue=2022-08-24 17:07:11,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=7,columnType=0,columnName=DESCRIPTION,columnValue=更新办,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=8,columnType=0,columnName=DETAILS,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=9,columnType=0,columnName=OPERATE_METHOD,columnValue=com.aoip.portal.schedule.controller.ScheduleController.updateSchedules,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=10,columnType=0,columnName=OPERATE_PARAM,columnValue=,isNull=true,isKey=false,isUpdate=true]
    EventColumn[index=11,columnType=3,columnName=TIME_TAKE,columnValue=175.000000000000000000000000000000,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=12,columnType=4,columnName=DEL_FLAG,columnValue=0,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=13,columnType=12,columnName=TENANT_ID,columnValue=2,isNull=false,isKey=false,isUpdate=true]
    EventColumn[index=14,columnType=4,columnName=VERSION,columnValue=0,isNull=false,isKey=false,isUpdate=true]
---Sql
    insert into `aoip_sys`.`sys_operate_log`(`OPERATOR_IP` , `OPERATOR_ID` , `OPERATOR_NAME` , `TYPE` , `STATUS` , `TIME` , `DESCRIPTION` , `DETAILS` , `OPERATE_METHOD` , `OPERATE_PARAM` , `TIME_TAKE` , `DEL_FLAG` , `TENANT_ID` , `VERSION` , `ID`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `OPERATOR_IP`=values(`OPERATOR_IP`) , `OPERATOR_ID`=values(`OPERATOR_ID`) , `OPERATOR_NAME`=values(`OPERATOR_NAME`) , `TYPE`=values(`TYPE`) , `STATUS`=values(`STATUS`) , `TIME`=values(`TIME`) , `DESCRIPTION`=values(`DESCRIPTION`) , `DETAILS`=values(`DETAILS`) , `OPERATE_METHOD`=values(`OPERATE_METHOD`) , `OPERATE_PARAM`=values(`OPERATE_PARAM`) , `TIME_TAKE`=values(`TIME_TAKE`) , `DEL_FLAG`=values(`DEL_FLAG`) , `TENANT_ID`=values(`TENANT_ID`) , `VERSION`=values(`VERSION`) , `ID`=values(`ID`)

**Comment by emf1002** [comment]
通过java代码 LogProxyClient 获取字段信息是正常的
![image](https://user-images.githubusercontent.com/559902/186390060-396186a1-f8ea-4868-aca8-3aa64ff42eaa.png)

**Comment by whhe** [comment]
> EventColumn[index=0,columnType=12,columnName=ID,columnValue=8421e71e140718d6cf7eac91591eeaa8,isNull=false,isKey=true,isUpdate=true] ---oldPks
> 
> ---Columns EventColumn[index=1,columnType=0,columnName=OPERATOR_IP,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=2,columnType=0,columnName=OPERATOR_ID,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=3,columnType=0,columnName=OPERATOR_NAME,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=4,columnType=0,columnName=TYPE,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=5,columnType=12,columnName=STATUS,columnValue=0001,isNull=false,isKey=false,isUpdate=true] EventColumn[index=6,columnType=93,columnName=TIME,columnValue=2022-08-24 17:07:11,isNull=false,isKey=false,isUpdate=true] EventColumn[index=7,columnType=0,columnName=DESCRIPTION,columnValue=更新办,isNull=false,isKey=false,isUpdate=true] EventColumn[index=8,columnType=0,columnName=DETAILS,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=9,columnType=0,columnName=OPERATE_METHOD,columnValue=com.aoip.portal.schedule.controller.ScheduleController.updateSchedules,isNull=false,isKey=false,isUpdate=true] EventColumn[index=10,columnType=0,columnName=OPERATE_PARAM,columnValue=,isNull=true,isKey=false,isUpdate=true] EventColumn[index=11,columnType=3,columnName=TIME_TAKE,columnValue=175.000000000000000000000000000000,isNull=false,isKey=false,isUpdate=true] EventColumn[index=12,columnType=4,columnName=DEL_FLAG,columnValue=0,isNull=false,isKey=false,isUpdate=true] EventColumn[index=13,columnType=12,columnName=TENANT_ID,columnValue=2,isNull=false,isKey=false,isUpdate=true] EventColumn[index=14,columnType=4,columnName=VERSION,columnValue=0,isNull=false,isKey=false,isUpdate=true] ---Sql insert into `aoip_sys`.`sys_operate_log`(`OPERATOR_IP` , `OPERATOR_ID` , `OPERATOR_NAME` , `TYPE` , `STATUS` , `TIME` , `DESCRIPTION` , `DETAILS` , `OPERATE_METHOD` , `OPERATE_PARAM` , `TIME_TAKE` , `DEL_FLAG` , `TENANT_ID` , `VERSION` , `ID`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `OPERATOR_IP`=values(`OPERATOR_IP`) , `OPERATOR_ID`=values(`OPERATOR_ID`) , `OPERATOR_NAME`=values(`OPERATOR_NAME`) , `TYPE`=values(`TYPE`) , `STATUS`=values(`STATUS`) , `TIME`=values(`TIME`) , `DESCRIPTION`=values(`DESCRIPTION`) , `DETAILS`=values(`DETAILS`) , `OPERATE_METHOD`=values(`OPERATE_METHOD`) , `OPERATE_PARAM`=values(`OPERATE_PARAM`) , `TIME_TAKE`=values(`TIME_TAKE`) , `DEL_FLAG`=values(`DEL_FLAG`) , `TENANT_ID`=values(`TENANT_ID`) , `VERSION`=values(`VERSION`) , `ID`=values(`ID`)

感谢反馈，看了下数据， `DESCRIPTION` 和 `OPERATE_METHOD`两个字段在有值的情况下 ColumnType 为 0 了，看了下字段类型，应该是跟这个问题相关的 https://github.com/oceanbase/oblogclient/issues/27，我会尽快找相关的研发进行修复，届时会更新 canal 和 otter 的安装包。

**Comment by whhe** [comment]
问题已修复，可以试下最新的包 https://github.com/oceanbase/canal/commit/2985de5b85ca5dbc0bc0f14bf183f4c8fabf96d8  https://github.com/oceanbase/canal/releases/tag/canal-for-ob-1.1.6-alpha
