### ISSUE TITLE
canal-for-ob 对 库表级的过滤不支持多个库表

### ISSUE THREAD

**Issue by wybsw520** [oceanbase/canal#25]
- [x] I have searched the [issues](https://github.com/alibaba/canal/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/alibaba/canal/wiki/FAQ) of this repository and believe that this is not a duplicate.

### environment
cdc同步ob增量数据到MQ
* canal version
1.1.6-alpha 1.1.7-alpha
* ob version
oceanbase-ce-4.2.1.3
oblogproxy-2.0.0-101000012023121819

### Issue Description
/Canal_Home/canal-for-ob/conf/example/instance.properties中的canal.instance.filter.regex参数设置为单表[tenant].[database].[table]，启动可以正常处理，设置为[tenant].[database].[table1]，[tenant].[database].[table2]时，启动日志报错，系统无法对oblogproxy设置过滤。

### Exception trace
```
2024-01-15 09:58:33.366 [log-proxy-client-worker-1-thread-1] INFO  com.oceanbase.clogproxy.client.connection.ClientHandler - ClientId: 192.168.100.157_1213369_1705283913: rootserver_list=192.168.100.157:2882:2881, cluster_user=root@obmysql#obce-single, cluster_password=******, tb_white_list=obmysql.meta.peri_item,obmysql.meta.catalog, tb_black_list=|, start_timestamp=0, timezone=+8:00, working_mode=storage connecting LogProxy: 192.168.100.157:2983
2024-01-15 09:58:33.367 [Thread-13] INFO  com.oceanbase.clogproxy.client.connection.ClientStream - Reconnect successfully
2024-01-15 09:58:33.571 [log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - LogProxy refused handshake request: code: 502
message: "Failed to parse configuration"

2024-01-15 09:58:33.572 [log-proxy-client-worker-1-thread-1] ERROR com.oceanbase.clogproxy.client.connection.ClientHandler - Exception occurred ClientId: 192.168.100.157_1213369_1705283913: rootserver_list=192.168.100.157:2882:2881, cluster_user=root@obmysql#obce-single, cluster_password=******, tb_white_list=obmysql.meta.peri_item,obmysql.meta.catalog, tb_black_list=|, start_timestamp=0, timezone=+8:00, working_mode=storage, with LogProxy: 192.168.100.157:2983
com.oceanbase.clogproxy.client.exception.LogProxyClientException: LogProxy refused handshake request: code: 502
message: "Failed to parse configuration"

	at com.oceanbase.clogproxy.client.connection.ClientHandler.handleErrorResponse(ClientHandler.java:217)
	at com.oceanbase.clogproxy.client.connection.ClientHandler.channelRead(ClientHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by whhe** [comment]
试试用 `|` 分隔。

**Comment by whhe** [comment]
我又检查了下，多条规则目前还是有点问题，稍等我更新一下正则参数的逻辑，之后你再试试吧。

**Comment by wybsw520** [comment]
> 之后你再试试吧
好的，你那边好了通知我一下，感谢

**Comment by whhe** [comment]
> > 之后你再试试吧
> > 好的，你那边好了通知我一下，感谢

更新过了，试下最新的配置文件，canal.instance.filter.regex 填库表名，格式 `schema1.tableName1,schema2.tableName2`

**Comment by whhe** [comment]
https://github.com/oceanbase/canal/releases/download/canal-for-ob-1.1.7-alpha/canal-for-ob.deployer.tar.gz

**Comment by wybsw520** [comment]
> > > 之后你再试试吧
> > > 好的，你那边好了通知我一下，感谢
> 
> 更新过了，试下最新的配置文件，canal.instance.filter.regex 填库表名，格式 `schema1.tableName1,schema2.tableName2`
> https://github.com/oceanbase/canal/releases/download/canal-for-ob-1.1.7-alpha/canal-for-ob.deployer.tar.gz

你好，请帮忙确认一下，使用最新官方下载【非镜像下载】1.1.7-alpha release版本搭配`schema1.tableName1,schema2.tableName2`这种格式后，从日志看可能有问题(日志第2行解析OK，日志第4行tb_white_list=obmysql.*.*可能不对)：
```
2024-01-15 16:52:51.393 [main] INFO  c.a.otter.canal.instance.spring.CanalInstanceWithSpring - start CannalInstance for 1-example 
2024-01-15 16:52:51.404 [main] WARN  c.alibaba.otter.canal.parse.inbound.AbstractBinlogParser - --> init table filter : ^meta.curriculum_detl$|^meta.asord_bib_data$|^meta.booklist_detl$|^meta.action_event$|^meta.credit_event$|^meta.loan_history$|^meta.catalog_detl$|^meta.domain_value$|^meta.e_pub_cover$|^meta.donate_list$|^meta.enum_value$|^meta.curriculum$|^meta.peri_item$|^meta.portfolio$|^meta.e_package$|^meta.e_package$|^meta.asord_bib$|^meta.bib_thumb$|^meta.imp_auth$|^meta.bib_data$|^meta.booklist$|^meta.catalog$|^meta.holding$|^meta.digital$|^meta.batch$|^meta.item$|^meta.menu$|^meta.bib$|^meta.var$
2024-01-15 16:52:51.405 [main] WARN  c.alibaba.otter.canal.parse.inbound.AbstractBinlogParser - --> init table black filter : 
2024-01-15 16:52:51.407 [main] INFO  c.a.otter.canal.instance.core.AbstractCanalInstance - start successful....
2024-01-15 16:52:51.408 [main] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - start CanalInstances[example] successfully
2024-01-15 16:52:51.415 [destination = example , address = /192.168.100.157:2983 , EventParser] INFO  c.a.o.c.p.inbound.oceanbase.logproxy.LogProxyEventParser - Connection config rootserver_list=192.168.100.157:2882:2881, cluster_user=root@obmysql#obce-single, cluster_password=******, tb_white_list=obmysql.*.*, tb_black_list=|, start_timestamp=0, timezone=+8:00, working_mode=storage
2024-01-15 16:52:51.426 [pool-4-thread-1] INFO  c.a.otter.canal.server.embedded.CanalServerWithEmbedded - subscribe successfully, ClientIdentity[destination=example,clientId=1001,filter=] with first position:null 
2024-01-15 16:52:51.433 [pool-4-thread-1] INFO  com.alibaba.otter.canal.server.CanalMQStarter - ## the MQ producer: example is running now ......
2024-01-15 16:52:51.564 [destination = example , address = /192.168.100.157:2983 , EventParser] INFO  c.a.o.c.p.inbound.oceanbase.logproxy.LogProxyEventParser - Client config {"clientId":"192.168.100.157_1291057_1705308771","connectTimeoutMs":5000,"idleTimeoutS":15,"ignoreUnknownRecordType":false,"maxReconnectTimes":-1,"nettyDiscardAfterReads":16,"readWaitTimeMs":2000,"retryIntervalS":2,"transferQueueSize":20000}

```

**Comment by whhe** [comment]
现在的逻辑是先取整个租户的增量日志，在格式转换的时候做过滤。
原因是 libobcdc 4.x 版本目前只能监听整个租户的变动，这个在之前的提交中做了一部分 https://github.com/oceanbase/canal/commit/ffbcb8376df5e88eef03a536b84083d64673064a ，只是当时的实现对正则匹配的处理有些问题，这一次做了修复。
